---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
#  vars:
#    ipv4_range: "192.168.0.0/16"
#    new_server_hostname: "teste123.example.com"
#    new_server_ip: "192.168.0.155"
#    nios_host: "129.146.209.37"
#    nios_user: "admin"
#    nios_passwd: "r3dh4t1!"
  tasks:      

  - name: return next available IP address for network {{ ipv4_range }}
    set_fact:
      ipaddr: "{{ lookup('nios_next_ip', ipv4_range, provider={'host': nios_host, 'username': nios_user, 'password': nios_passwd}) }}"
    register: nios_next_ip

  - debug:
      msg: "nios_next_ip = {{ nios_next_ip }} / {{ nios_next_ip.ansible_facts.ipaddr[0] }}"

  - set_fact:
      new_server_ip: "{{ nios_next_ip.ansible_facts.ipaddr[0] }}"

  - debug:
      msg: "new_server_ip = {{ new_server_ip }}"

  - name: Add host as A record
    nios_a_record:
      name: "{{ new_server_hostname }}"
      ipv4: "{{ new_server_ip }}"
      state: present
      provider:
        host: "{{ nios_host }}"
        username: "{{ nios_user }}"
        password: "{{ nios_passwd }}"
    connection: local

  - name: Add host as PTR record
    nios_ptr_record:
      ptrdname: "{{ new_server_hostname }}"
      ipv4: "{{ new_server_ip }}"
      state: present
      provider:
        host: "{{ nios_host }}"
        username: "{{ nios_user }}"
        password: "{{ nios_passwd }}"
    connection: local    

  - name: Update Task with New IP and Hostname Information
    uri:
      url: "{{ manageiq.api_url }}/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
      method: POST
      body_format: json
      body:
        action: edit
        resource:
          options:
            addr_mode: ["static", "Static"]
            ip_addr: "{{ new_server_ip }}"
            subnet_mask: "{{ new_server_subnet }}"
            gateway: "{{ new_server_gateway }}"
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      status_code: 200